global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'traffic-edge-devices'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          device: 'edge_001'
          intersection: 'mg_road'
