global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'traffic-edge-devices'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          device: 'edge_001'
          intersection: 'mg_road'
          
  - job_name: 'infrastructure'
    static_configs:
      - targets:
        - 'mqtt:1883'
        - 'influxdb:8086'
        - 'redis:6379'
